# Generated by Django 2.0.7 on 2018-09-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
